# Generated by Django 4.1.5 on 2024-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_patron'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
