# Generated by Django 4.1.5 on 2024-08-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0006_sponsorbenefit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsorbenefit",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="sponsorbenefit",
            name="sponsor_level",
        ),
        migrations.CreateModel(
            name="BenefitByLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer", models.PositiveIntegerField(help_text="제공 하는 혜택 개수")),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_by_level",
                        to="sponsor.sponsorbenefit",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_by_level",
                        to="sponsor.sponsorlevel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="benefitbylevel",
            constraint=models.UniqueConstraint(
                fields=("benefit_id", "level_id"), name="IX_BENEFIT_BY_LEVEL_1"
            ),
        ),
    ]
