# Generated by Django 4.1.5 on 2024-08-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0006_sponsorlevel_year"),
        ("sponsor", "0007_remove_sponsorbenefit_offer_and_more"),
    ]

    operations = []
