# Generated by Django 4.1.5 on 2024-08-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0008_merge_20240806_2206"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorbenefit",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="sponsorlevel",
            name="benefits",
            field=models.ManyToManyField(
                related_name="level",
                through="sponsor.BenefitByLevel",
                to="sponsor.sponsorbenefit",
            ),
        ),
    ]
