# Generated by Django 4.1.5 on 2024-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0009_sponsorbenefit_year_sponsorlevel_benefits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefitbylevel",
            options={
                "verbose_name": "후원사 등급별 혜택",
                "verbose_name_plural": "후원사 등급별 혜택 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="sponsorbenefit",
            options={
                "verbose_name": "후원사 혜택",
                "verbose_name_plural": "후원사 혜택 목록",
            },
        ),
        migrations.AddField(
            model_name="benefitbylevel",
            name="uncountable_offer",
            field=models.TextField(blank=True, help_text="셀 수 없는 혜택", null=True),
        ),
        migrations.AlterField(
            model_name="benefitbylevel",
            name="offer",
            field=models.PositiveIntegerField(
                help_text="제공 하는 혜택 개수", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorbenefit",
            name="unit",
            field=models.CharField(
                blank=True, help_text="혜택 단위", max_length=10, null=True
            ),
        ),
    ]
