# Generated by Django 4.1.5 on 2024-09-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0010_alter_benefitbylevel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefitbylevel",
            name="offer",
            field=models.PositiveIntegerField(
                blank=True, help_text="제공 하는 혜택 개수", null=True
            ),
        ),
    ]
