# Generated by Django 4.1.5 on 2024-09-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0011_alter_benefitbylevel_offer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsorlevel",
            options={
                "ordering": ["order"],
                "verbose_name": "후원사 등급",
                "verbose_name_plural": "후원사 등급",
            },
        ),
    ]
