# Generated by Django 4.1.5 on 2023-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_rename_user_id_payment_user_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="is_webhook",
            field=models.BooleanField(default=False),
        ),
    ]
