# Generated by Django 4.1.5 on 2023-07-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="accepted",
        ),
    ]
