# Generated by Django 4.1.5 on 2023-07-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0002_remove_session_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="host_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="발표 소개 페이지에 들어가는 내용입니다.",
                max_length=3000,
                null=True,
            ),
        ),
    ]
