# Generated by Django 4.1.5 on 2023-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0003_session_host_name_alter_session_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="duration",
            field=models.CharField(
                choices=[("SHORT", "20min"), ("LONG", "40min")], max_length=15
            ),
        ),
    ]
