# Generated by Django 4.1.5 on 2023-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0004_alter_session_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="host_introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="host_profile_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
