# Generated by Django 4.1.5 on 2024-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_session_host_introduction_session_host_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
