# Generated by Django 4.1.5 on 2023-03-01 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "brief",
                    models.TextField(help_text="리뷰용: 발표에 대한 간단한 설명.", max_length=1000),
                ),
                (
                    "desc",
                    models.TextField(help_text="리뷰용: 발표에 대한 자세한 설명", max_length=4000),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="리뷰용: 파준위에게 전하고 싶은 말",
                        max_length=4000,
                        null=True,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("EXPERIENCED", "Experienced"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[("SHORT", "25min"), ("LONG", "40min")], max_length=15
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("", "---------"),
                            ("KOREAN", "Korean"),
                            ("ENGLISH", "English"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="발표 소개 페이지에 들어가는 내용입니다. 변경 사항은 최대 60분 이내에 적용됩니다.",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True, help_text="발표 영상 URL", max_length=255, null=True
                    ),
                ),
                (
                    "slide_url",
                    models.CharField(
                        blank=True, help_text="발표 자료 URL", max_length=255, null=True
                    ),
                ),
                (
                    "room_num",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("101", "101"),
                            ("102", "102"),
                            ("103", "103"),
                            ("104", "104"),
                            ("105", "105"),
                        ],
                        help_text="발표장소",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=14,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="program.proposalcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
