# Generated by Django 4.1.5 on 2023-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_proposal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=4000)),
                ('room', models.CharField(blank=True, choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('201', '201'), ('202', '202'), ('203', '203')], max_length=15, null=True)),
                ('capacity', models.IntegerField(blank=True, help_text='최대 참가 가능 인원 수', null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('program_type', models.CharField(choices=[('CONFERENCE', '컨퍼런스'), ('TUTORIAL', '튜토리얼'), ('SPRINT', '스프린트')], max_length=30)),
            ],
        ),
    ]
