# Generated by Django 4.1.5 on 2023-07-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0005_alter_program_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={"verbose_name": "프로그램", "verbose_name_plural": "프로그램들"},
        ),
        migrations.DeleteModel(
            name="Proposal",
        ),
        migrations.DeleteModel(
            name="ProposalCategory",
        ),
    ]
