# Generated by Django 4.1.5 on 2023-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0006_alter_program_options_delete_proposal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
