# Generated by Django 4.1.5 on 2024-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_alter_program_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
