# Generated by Django 4.1.5 on 2023-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencetickettype',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
