# Generated by Django 4.1.5 on 2023-05-15 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_rename_user_id_payment_user_payment_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0002_rename_conferencetickettype_tickettype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bought_at", models.DateTimeField()),
                (
                    "ticket_code",
                    models.CharField(
                        db_index=True,
                        default=ticket.models.make_ticket_code,
                        max_length=25,
                        unique=True,
                    ),
                ),
                ("is_refunded", models.BooleanField(default=False)),
                ("refunded_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment.payment",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="tickettype",
            name="code",
        ),
        migrations.AddField(
            model_name="tickettype",
            name="is_refundable",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="ConferenceTicket",
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="ticket.tickettype"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
