# Generated by Django 4.1.5 on 2023-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_tickettype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='day',
            field=models.CharField(choices=[('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일'), ('WEEKEND', '토/일요일')], max_length=10),
        ),
    ]
