# Generated by Django 4.1.5 on 2023-05-30 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_tickettype_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
