# Generated by Django 4.1.5 on 2023-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_refunded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='buyable_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
